package renderer

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/larsenclose/oci-tf-bootstrap/internal/discovery"
)

func writeDataSources(result *discovery.Result, outputDir string) error {
	f, err := os.Create(filepath.Join(outputDir, "data.tf"))
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "# Generated by oci-tf-bootstrap")
	fmt.Fprintln(f, "# Dynamic data sources - these stay valid as images update")
	fmt.Fprintln(f, "")

	fmt.Fprintln(f, "# Availability Domains")
	fmt.Fprintln(f, `data "oci_identity_availability_domains" "ads" {`)
	fmt.Fprintln(f, "  compartment_id = local.tenancy_ocid")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")

	seenOS := make(map[string]bool)
	for _, img := range result.Images {
		key := img.OS + "-" + img.OSVersion
		if seenOS[key] {
			continue
		}
		seenOS[key] = true

		name := toTFName(img.OS + "_" + img.OSVersion)
		fmt.Fprintf(f, "# Latest %s %s\n", img.OS, img.OSVersion)
		fmt.Fprintf(f, `data "oci_core_images" "%s" {`+"\n", name)
		fmt.Fprintln(f, "  compartment_id           = local.tenancy_ocid")
		fmt.Fprintf(f, "  operating_system         = %q\n", img.OS)
		fmt.Fprintf(f, "  operating_system_version = %q\n", img.OSVersion)
		fmt.Fprintln(f, "  sort_by                  = \"TIMECREATED\"")
		fmt.Fprintln(f, "  sort_order               = \"DESC\"")
		fmt.Fprintln(f, "  state                    = \"AVAILABLE\"")
		fmt.Fprintln(f, "}")
		fmt.Fprintln(f, "")
	}

	fmt.Fprintln(f, "# Helper outputs for easy reference")
	fmt.Fprintln(f, `output "availability_domains" {`)
	fmt.Fprintln(f, `  description = "Map of AD names"`)
	fmt.Fprintln(f, "  value = {")
	for i := range result.AvailabilityDomains {
		fmt.Fprintf(f, "    ad_%d = data.oci_identity_availability_domains.ads.availability_domains[%d].name\n", i+1, i)
	}
	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")

	if len(result.Images) > 0 {
		fmt.Fprintln(f, `output "latest_images" {`)
		fmt.Fprintln(f, `  description = "Latest image OCIDs by OS"`)
		fmt.Fprintln(f, "  value = {")
		seenOS = make(map[string]bool)
		for _, img := range result.Images {
			key := img.OS + "-" + img.OSVersion
			if seenOS[key] {
				continue
			}
			seenOS[key] = true
			name := toTFName(img.OS + "_" + img.OSVersion)
			fmt.Fprintf(f, "    %s = data.oci_core_images.%s.images[0].id\n", name, name)
		}
		fmt.Fprintln(f, "  }")
		fmt.Fprintln(f, "}")
	}

	return nil
}
