package renderer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/larsenclose/oci-tf-bootstrap/internal/discovery"
)

// findSSHKeyPath checks for common SSH public key files and returns the path if found
func findSSHKeyPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}

	// Check common SSH key paths in order of preference
	keyPaths := []string{
		filepath.Join(home, ".ssh", "id_ed25519.pub"),
		filepath.Join(home, ".ssh", "id_rsa.pub"),
		filepath.Join(home, ".ssh", "id_ecdsa.pub"),
	}

	for _, path := range keyPaths {
		if _, err := os.Stat(path); err == nil {
			return path
		}
	}
	return ""
}

func writeInstanceExample(result *discovery.Result, outputDir string, opts Options) error {
	f, err := os.Create(filepath.Join(outputDir, "instance_example.tf")) // #nosec G304 -- outputDir is user-specified CLI flag
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "# Generated by oci-tf-bootstrap")

	if opts.AlwaysFree {
		writeAlwaysFreeInstance(f, result)
	} else {
		writeStandardInstance(f, result)
	}

	return nil
}

func writeAlwaysFreeInstance(f *os.File, result *discovery.Result) {
	fmt.Fprintln(f, "# Always-Free Tier Instance Example")
	fmt.Fprintln(f, "#")
	fmt.Fprintln(f, "# Free tier limits for VM.Standard.A1.Flex (ARM):")
	fmt.Fprintln(f, "#   - 4 OCPUs total across ALL A1 instances in tenancy")
	fmt.Fprintln(f, "#   - 24GB memory total across ALL A1 instances in tenancy")
	fmt.Fprintln(f, "#   - This example uses 2 OCPU / 12GB (half the free allocation)")
	fmt.Fprintln(f, "#   - You can create 2 instances with these specs, or 1 instance with 4/24")
	fmt.Fprintln(f, "#")
	fmt.Fprintln(f, "# Boot volume is included in the 200GB free block storage limit")
	fmt.Fprintln(f, "#")
	fmt.Fprintln(f, "# WARNING: A1.Flex capacity varies by AD. If you get 'Out of Capacity' errors,")
	fmt.Fprintln(f, "#          try changing availability_domain to ad_2 or ad_3 below.")
	fmt.Fprintln(f, "")

	// Find ARM64 Ubuntu image first, then fall back to any ARM64 image
	var imageKey string
	for _, img := range result.Images {
		version := strings.ToLower(img.OSVersion)
		if img.OS == "Canonical Ubuntu" && strings.Contains(version, "aarch64") {
			imageKey = toTFName(img.OS + "_" + img.OSVersion)
			break
		}
	}
	// Fallback to any aarch64 image
	if imageKey == "" {
		for _, img := range result.Images {
			version := strings.ToLower(img.OSVersion)
			if strings.Contains(version, "aarch64") {
				imageKey = toTFName(img.OS + "_" + img.OSVersion)
				break
			}
		}
	}
	// Final fallback to first image
	if imageKey == "" && len(result.Images) > 0 {
		img := result.Images[0]
		imageKey = toTFName(img.OS + "_" + img.OSVersion)
	}

	fmt.Fprintln(f, `resource "oci_core_instance" "always_free" {`)
	fmt.Fprintln(f, "  compartment_id      = local.tenancy_ocid")
	fmt.Fprintln(f, "  availability_domain = local.ad_1")
	fmt.Fprintln(f, `  display_name        = "always-free-arm"`)
	fmt.Fprintln(f, "")

	if imageKey != "" {
		fmt.Fprintln(f, "  source_details {")
		fmt.Fprintf(f, "    source_id               = data.oci_core_images.%s.images[0].id\n", imageKey)
		fmt.Fprintln(f, `    source_type             = "image"`)
		fmt.Fprintln(f, "    boot_volume_size_in_gbs = 50  # Counts toward 200GB free limit")
		fmt.Fprintln(f, "  }")
		fmt.Fprintln(f, "")
	}

	// Check if A1.Flex is available
	hasA1Flex := false
	for _, s := range result.Shapes {
		if s.Name == "VM.Standard.A1.Flex" {
			hasA1Flex = true
			break
		}
	}

	if hasA1Flex {
		fmt.Fprintln(f, `  shape = "VM.Standard.A1.Flex"  # ARM-based, always-free eligible`)
		fmt.Fprintln(f, "")
		fmt.Fprintln(f, "  shape_config {")
		fmt.Fprintln(f, "    ocpus         = 2   # Half of 4 free OCPUs (allows 2 instances)")
		fmt.Fprintln(f, "    memory_in_gbs = 12  # Half of 24GB free (allows 2 instances)")
		fmt.Fprintln(f, "  }")
	} else {
		fmt.Fprintln(f, `  # WARNING: VM.Standard.A1.Flex not available in this tenancy/region`)
		fmt.Fprintln(f, `  # You may need to request a service limit increase`)
		fmt.Fprintln(f, `  shape = "VM.Standard.E2.1.Micro"  # x86, 2 free instances`)
	}
	fmt.Fprintln(f, "")

	fmt.Fprintln(f, "  create_vnic_details {")
	fmt.Fprintln(f, "    assign_public_ip = true  # Free for always-free instances")

	if len(result.VCNs) > 0 && len(result.VCNs[0].Subnets) > 0 {
		// Prefer public subnet for always-free (no NAT gateway needed)
		var subnetName string
		for _, s := range result.VCNs[0].Subnets {
			if s.IsPublic {
				subnetName = toTFName(s.DisplayName)
				break
			}
		}
		if subnetName == "" {
			subnetName = toTFName(result.VCNs[0].Subnets[0].DisplayName)
		}
		fmt.Fprintf(f, "    subnet_id        = local.subnet_%s\n", subnetName)
	} else {
		fmt.Fprintln(f, "    # Use the bootstrap subnet from network.tf, or uncomment after creating your own:")
		fmt.Fprintln(f, "    subnet_id = oci_core_subnet.public.id")
		fmt.Fprintln(f, "    # subnet_id = local.subnet_<your_subnet_name>")
	}

	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "")

	// Check for SSH key and include it if found
	sshKeyPath := findSSHKeyPath()
	if sshKeyPath != "" {
		fmt.Fprintln(f, "  metadata = {")
		fmt.Fprintf(f, "    ssh_authorized_keys = file(%q)\n", sshKeyPath)
		fmt.Fprintln(f, "  }")
	} else {
		fmt.Fprintln(f, "  # Optional: Add SSH key for access")
		fmt.Fprintln(f, "  # metadata = {")
		fmt.Fprintln(f, `  #   ssh_authorized_keys = file("~/.ssh/id_rsa.pub")`)
		fmt.Fprintln(f, "  # }")
	}
	fmt.Fprintln(f, "}")
}

func writeStandardInstance(f *os.File, result *discovery.Result) {
	fmt.Fprintln(f, "# Example instance using discovered locals and data sources")
	fmt.Fprintln(f, "")

	var imageKey string
	for _, img := range result.Images {
		if img.OS == "Canonical Ubuntu" {
			imageKey = toTFName(img.OS + "_" + img.OSVersion)
			break
		}
	}

	if imageKey == "" && len(result.Images) > 0 {
		img := result.Images[0]
		imageKey = toTFName(img.OS + "_" + img.OSVersion)
	}

	fmt.Fprintln(f, `resource "oci_core_instance" "example" {`)
	fmt.Fprintln(f, "  compartment_id      = local.tenancy_ocid")
	fmt.Fprintln(f, "  availability_domain = local.ad_1")
	fmt.Fprintln(f, `  display_name        = "example-instance"`)
	fmt.Fprintln(f, "")

	if imageKey != "" {
		fmt.Fprintln(f, "  source_details {")
		fmt.Fprintf(f, "    source_id   = data.oci_core_images.%s.images[0].id\n", imageKey)
		fmt.Fprintln(f, `    source_type = "image"`)
		fmt.Fprintln(f, "  }")
		fmt.Fprintln(f, "")
	}

	fmt.Fprintln(f, `  shape = "VM.Standard.E4.Flex"`)
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "  shape_config {")
	fmt.Fprintln(f, "    ocpus         = 1")
	fmt.Fprintln(f, "    memory_in_gbs = 6")
	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "  create_vnic_details {")
	fmt.Fprintln(f, "    assign_public_ip = true")

	if len(result.VCNs) > 0 && len(result.VCNs[0].Subnets) > 0 {
		subnetName := toTFName(result.VCNs[0].Subnets[0].DisplayName)
		fmt.Fprintf(f, "    subnet_id        = local.subnet_%s\n", subnetName)
	} else {
		fmt.Fprintln(f, "    # Use the bootstrap subnet from network.tf, or uncomment after creating your own:")
		fmt.Fprintln(f, "    subnet_id = oci_core_subnet.public.id")
		fmt.Fprintln(f, "    # subnet_id = local.subnet_<your_subnet_name>")
	}

	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "")

	// Check for SSH key and include it if found
	sshKeyPath := findSSHKeyPath()
	if sshKeyPath != "" {
		fmt.Fprintln(f, "  metadata = {")
		fmt.Fprintf(f, "    ssh_authorized_keys = file(%q)\n", sshKeyPath)
		fmt.Fprintln(f, "  }")
	} else {
		fmt.Fprintln(f, "  # metadata = {")
		fmt.Fprintln(f, `  #   ssh_authorized_keys = file("~/.ssh/id_rsa.pub")`)
		fmt.Fprintln(f, "  # }")
	}
	fmt.Fprintln(f, "}")
}
