package renderer

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/larsenclose/oci-tf-bootstrap/internal/discovery"
)

// writeNetwork generates a basic VCN and subnet configuration when none exist
func writeNetwork(result *discovery.Result, outputDir string, opts Options) error {
	// Only generate if no VCNs were discovered
	if len(result.VCNs) > 0 {
		return nil
	}

	f, err := os.Create(filepath.Join(outputDir, "network.tf")) // #nosec G304 -- outputDir is user-specified CLI flag
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintln(f, "# Generated by oci-tf-bootstrap")
	fmt.Fprintln(f, "# Basic VCN configuration - no existing VCN was discovered")
	fmt.Fprintln(f, "#")
	if opts.AlwaysFree {
		fmt.Fprintln(f, "# Note: VCN and networking resources are FREE in OCI always-free tier")
		fmt.Fprintln(f, "# You get 2 VCNs with all gateways included at no cost")
		fmt.Fprintln(f, "")
	}

	// VCN
	fmt.Fprintln(f, `resource "oci_core_vcn" "main" {`)
	fmt.Fprintln(f, "  compartment_id = local.tenancy_ocid")
	fmt.Fprintln(f, `  cidr_blocks    = ["10.0.0.0/16"]`)
	fmt.Fprintln(f, `  display_name   = "bootstrap-vcn"`)
	fmt.Fprintln(f, `  dns_label      = "bootstrap"`)
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")

	// Internet Gateway
	fmt.Fprintln(f, `resource "oci_core_internet_gateway" "main" {`)
	fmt.Fprintln(f, "  compartment_id = local.tenancy_ocid")
	fmt.Fprintln(f, "  vcn_id         = oci_core_vcn.main.id")
	fmt.Fprintln(f, `  display_name   = "bootstrap-igw"`)
	fmt.Fprintln(f, "  enabled        = true")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")

	// Route Table
	fmt.Fprintln(f, `resource "oci_core_route_table" "public" {`)
	fmt.Fprintln(f, "  compartment_id = local.tenancy_ocid")
	fmt.Fprintln(f, "  vcn_id         = oci_core_vcn.main.id")
	fmt.Fprintln(f, `  display_name   = "bootstrap-public-rt"`)
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "  route_rules {")
	fmt.Fprintln(f, `    destination       = "0.0.0.0/0"`)
	fmt.Fprintln(f, `    destination_type  = "CIDR_BLOCK"`)
	fmt.Fprintln(f, "    network_entity_id = oci_core_internet_gateway.main.id")
	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")

	// Security List
	fmt.Fprintln(f, `resource "oci_core_security_list" "public" {`)
	fmt.Fprintln(f, "  compartment_id = local.tenancy_ocid")
	fmt.Fprintln(f, "  vcn_id         = oci_core_vcn.main.id")
	fmt.Fprintln(f, `  display_name   = "bootstrap-public-sl"`)
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "  # Allow all egress")
	fmt.Fprintln(f, "  egress_security_rules {")
	fmt.Fprintln(f, `    destination = "0.0.0.0/0"`)
	fmt.Fprintln(f, `    protocol    = "all"`)
	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "  # Allow SSH")
	fmt.Fprintln(f, "  ingress_security_rules {")
	fmt.Fprintln(f, `    source   = "0.0.0.0/0"`)
	fmt.Fprintln(f, `    protocol = "6"  # TCP`)
	fmt.Fprintln(f, "    tcp_options {")
	fmt.Fprintln(f, "      min = 22")
	fmt.Fprintln(f, "      max = 22")
	fmt.Fprintln(f, "    }")
	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "  # Allow ICMP (ping)")
	fmt.Fprintln(f, "  ingress_security_rules {")
	fmt.Fprintln(f, `    source   = "0.0.0.0/0"`)
	fmt.Fprintln(f, `    protocol = "1"  # ICMP`)
	fmt.Fprintln(f, "    icmp_options {")
	fmt.Fprintln(f, "      type = 3")
	fmt.Fprintln(f, "      code = 4")
	fmt.Fprintln(f, "    }")
	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "  ingress_security_rules {")
	fmt.Fprintln(f, `    source   = "0.0.0.0/0"`)
	fmt.Fprintln(f, `    protocol = "1"`)
	fmt.Fprintln(f, "    icmp_options {")
	fmt.Fprintln(f, "      type = 8")
	fmt.Fprintln(f, "    }")
	fmt.Fprintln(f, "  }")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")

	// Public Subnet
	fmt.Fprintln(f, `resource "oci_core_subnet" "public" {`)
	fmt.Fprintln(f, "  compartment_id             = local.tenancy_ocid")
	fmt.Fprintln(f, "  vcn_id                     = oci_core_vcn.main.id")
	fmt.Fprintln(f, `  cidr_block                 = "10.0.0.0/24"`)
	fmt.Fprintln(f, `  display_name               = "bootstrap-public-subnet"`)
	fmt.Fprintln(f, `  dns_label                  = "public"`)
	fmt.Fprintln(f, "  route_table_id             = oci_core_route_table.public.id")
	fmt.Fprintln(f, "  security_list_ids          = [oci_core_security_list.public.id]")
	fmt.Fprintln(f, "  prohibit_public_ip_on_vnic = false")
	fmt.Fprintln(f, "}")
	fmt.Fprintln(f, "")

	// Output
	fmt.Fprintln(f, "# Use this subnet in your instance:")
	fmt.Fprintln(f, `output "bootstrap_subnet_id" {`)
	fmt.Fprintln(f, `  description = "Subnet ID for bootstrap instances"`)
	fmt.Fprintln(f, "  value       = oci_core_subnet.public.id")
	fmt.Fprintln(f, "}")

	return nil
}
