package renderer

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/larsenclose/oci-tf-bootstrap/internal/discovery"
)

// okeVersionGroup holds OKE images grouped by Kubernetes version
type okeVersionGroup struct {
	version string
	arm     *discovery.OKEImage
	x86     *discovery.OKEImage
}

// compareVersions compares two semver strings (e.g. "v1.32.10" vs "v1.31.10").
// Returns negative if a < b, zero if equal, positive if a > b.
func compareVersions(a, b string) int {
	partsA := strings.Split(strings.TrimPrefix(a, "v"), ".")
	partsB := strings.Split(strings.TrimPrefix(b, "v"), ".")

	for i := 0; i < len(partsA) && i < len(partsB); i++ {
		// Compare numerically by padding with zeros
		pa := partsA[i]
		pb := partsB[i]
		// Simple numeric comparison via string padding
		maxLen := len(pa)
		if len(pb) > maxLen {
			maxLen = len(pb)
		}
		for len(pa) < maxLen {
			pa = "0" + pa
		}
		for len(pb) < maxLen {
			pb = "0" + pb
		}
		if pa < pb {
			return -1
		}
		if pa > pb {
			return 1
		}
	}
	return len(partsA) - len(partsB)
}

// groupOKEImagesByVersion groups OKE images by Kubernetes version and architecture,
// returning groups sorted by version descending (latest first).
func groupOKEImagesByVersion(images []discovery.OKEImage) []okeVersionGroup {
	byVersion := make(map[string]*okeVersionGroup)

	for i := range images {
		img := &images[i]
		g, ok := byVersion[img.KubernetesVersion]
		if !ok {
			g = &okeVersionGroup{version: img.KubernetesVersion}
			byVersion[img.KubernetesVersion] = g
		}
		switch img.Architecture {
		case "aarch64":
			if g.arm == nil {
				g.arm = img
			}
		case "x86_64":
			if g.x86 == nil {
				g.x86 = img
			}
		}
	}

	groups := make([]okeVersionGroup, 0, len(byVersion))
	for _, g := range byVersion {
		groups = append(groups, *g)
	}

	// Sort descending by version (latest first)
	sort.Slice(groups, func(i, j int) bool {
		return compareVersions(groups[i].version, groups[j].version) > 0
	})

	return groups
}

// okeLocalName returns the local variable name used for an OKE image in locals.tf.
// This must match the naming convention in writeLocals (locals.go), which builds:
//
//	versionKey := strings.ReplaceAll(img.KubernetesVersion, ".", "_")
//	base := versionKey + "_" + toTFName(img.Architecture)
//	name := okeTracker.unique(base)  // unique calls toTFName(base) internally
//
// So the full name is "oke_image_" + toTFName(versionKey + "_" + toTFName(arch)).
func okeLocalName(img *discovery.OKEImage) string {
	versionKey := strings.ReplaceAll(img.KubernetesVersion, ".", "_")
	base := versionKey + "_" + toTFName(img.Architecture)
	return "oke_image_" + toTFName(base)
}

func writeOKEExample(result *discovery.Result, outputDir string, opts Options) (err error) {
	if len(result.OKEImages) == 0 {
		return nil
	}

	f, err := os.Create(filepath.Join(outputDir, "oke_example.tf")) // #nosec G304 -- outputDir is user-specified CLI flag
	if err != nil {
		return err
	}
	defer func() {
		if cerr := f.Close(); cerr != nil && err == nil {
			err = cerr
		}
	}()

	fmt.Fprintln(f, "# Generated by oci-tf-bootstrap")
	fmt.Fprintln(f, "# OKE (Oracle Kubernetes Engine) Node Pool Examples")
	fmt.Fprintln(f, "#")
	fmt.Fprintln(f, "# These are REFERENCE configurations. Before using, you must:")
	fmt.Fprintln(f, "#   1. Create an OKE cluster (or reference an existing one)")
	fmt.Fprintln(f, "#   2. Replace PLACEHOLDER_CLUSTER_OCID with your cluster's OCID")
	fmt.Fprintln(f, "#   3. Update subnet references to match your network configuration")
	fmt.Fprintln(f, "#   4. Adjust node counts and shape configurations as needed")

	if opts.AlwaysFree {
		fmt.Fprintln(f, "#")
		fmt.Fprintln(f, "# Always-Free Tier Notes:")
		fmt.Fprintln(f, "#   - OKE control plane is FREE (Oracle manages it)")
		fmt.Fprintln(f, "#   - Worker nodes consume your Always-Free compute quota")
		fmt.Fprintln(f, "#   - VM.Standard.A1.Flex (ARM): 4 OCPUs + 24GB total across ALL A1 instances")
		fmt.Fprintln(f, "#   - Node pool sizing below uses 2 OCPU / 12GB per node (half the free quota)")
		fmt.Fprintln(f, "#   - You likely can only run 1-2 worker nodes within free tier limits")
	}

	fmt.Fprintln(f, "")

	groups := groupOKEImagesByVersion(result.OKEImages)

	for i, g := range groups {
		isLatest := i == 0
		commented := !isLatest

		writeVersionHeader(f, g, isLatest, commented)

		if g.arm != nil {
			writeARMNodePool(f, g, opts, commented)
		}

		if g.x86 != nil {
			writeX86NodePool(f, g, opts, commented)
		}
	}

	fmt.Fprintln(f, "# ── Adding More Node Pools ──────────────────────────────────────────────────")
	fmt.Fprintln(f, "#")
	fmt.Fprintln(f, "# To add more node pools, copy one of the resource blocks above and change:")
	fmt.Fprintln(f, "#   - The resource name (e.g. \"gpu_pool\", \"highmem_pool\")")
	fmt.Fprintln(f, "#   - node_shape to the desired shape (e.g. \"VM.GPU.A10.1\", \"VM.Standard.E5.Flex\")")
	fmt.Fprintln(f, "#   - node_shape_config for flex shapes (ocpus and memory_in_gbs)")
	fmt.Fprintln(f, "#   - size in node_config_details for the desired node count")

	return nil
}

func writeVersionHeader(f *os.File, g okeVersionGroup, isLatest bool, commented bool) {
	p := lineWriter(commented)

	if isLatest {
		fmt.Fprintf(f, "\n# ── Kubernetes %s (latest) ─────────────────────────────────────────────\n", g.version)
	} else {
		fmt.Fprintln(f, "")
		p(f, fmt.Sprintf("# ── Kubernetes %s ─────────────────────────────────────────────────────", g.version))
		p(f, "# Uncomment the node pools below to use this version instead.")
	}
	fmt.Fprintln(f, "")
}

func writeARMNodePool(f *os.File, g okeVersionGroup, opts Options, commented bool) {
	p := lineWriter(commented)
	localName := okeLocalName(g.arm)

	var ocpus, memGB string
	if opts.AlwaysFree {
		ocpus = "2   # Half of 4 free OCPUs (fits 1-2 nodes in free tier)"
		memGB = "12  # Half of 24GB free memory"
	} else {
		ocpus = "2"
		memGB = "12"
	}

	p(f, fmt.Sprintf(`resource "oci_containerengine_node_pool" "arm_pool_%s" {`, toTFName(g.version)))
	p(f, "  compartment_id     = local.compartment_ocid")
	p(f, `  cluster_id         = "PLACEHOLDER_CLUSTER_OCID"  # Replace with your OKE cluster OCID`)
	p(f, fmt.Sprintf("  kubernetes_version = %q", g.version))
	p(f, fmt.Sprintf(`  name               = "arm-pool-%s"`, strings.ReplaceAll(strings.TrimPrefix(g.version, "v"), ".", "-")))
	p(f, "")
	p(f, `  # ARM-based shape: best price-performance ratio`)
	p(f, `  node_shape = "VM.Standard.A1.Flex"`)
	p(f, "  node_shape_config {")
	p(f, fmt.Sprintf("    ocpus         = %s", ocpus))
	p(f, fmt.Sprintf("    memory_in_gbs = %s", memGB))
	p(f, "  }")
	p(f, "")
	p(f, "  node_source_details {")
	p(f, `    source_type = "IMAGE"`)
	p(f, fmt.Sprintf("    image_id    = local.%s", localName))
	p(f, "  }")
	p(f, "")
	if opts.AlwaysFree {
		p(f, "  node_config_details {")
		p(f, "    size = 1  # Keep to 1 node to stay within free tier limits")
	} else {
		p(f, "  node_config_details {")
		p(f, "    size = 1  # Number of worker nodes")
	}
	p(f, "    placement_configs {")
	p(f, "      availability_domain = local.ad_1")
	p(f, `      subnet_id           = "PLACEHOLDER_SUBNET_OCID"  # Replace with your worker subnet OCID`)
	p(f, "    }")
	p(f, "  }")
	p(f, "}")
	fmt.Fprintln(f, "")
}

func writeX86NodePool(f *os.File, g okeVersionGroup, opts Options, commented bool) {
	p := lineWriter(commented)
	localName := okeLocalName(g.x86)

	p(f, fmt.Sprintf(`resource "oci_containerengine_node_pool" "x86_pool_%s" {`, toTFName(g.version)))
	p(f, "  compartment_id     = local.compartment_ocid")
	p(f, `  cluster_id         = "PLACEHOLDER_CLUSTER_OCID"  # Replace with your OKE cluster OCID`)
	p(f, fmt.Sprintf("  kubernetes_version = %q", g.version))
	p(f, fmt.Sprintf(`  name               = "x86-pool-%s"`, strings.ReplaceAll(strings.TrimPrefix(g.version, "v"), ".", "-")))
	p(f, "")
	p(f, `  # x86-based shape: broad compatibility`)
	p(f, `  node_shape = "VM.Standard.E4.Flex"`)
	p(f, "  node_shape_config {")
	p(f, "    ocpus         = 2")
	p(f, "    memory_in_gbs = 16")
	p(f, "  }")
	p(f, "")
	p(f, "  node_source_details {")
	p(f, `    source_type = "IMAGE"`)
	p(f, fmt.Sprintf("    image_id    = local.%s", localName))
	p(f, "  }")
	p(f, "")
	p(f, "  node_config_details {")
	p(f, "    size = 1  # Number of worker nodes")
	p(f, "    placement_configs {")
	p(f, "      availability_domain = local.ad_1")
	p(f, `      subnet_id           = "PLACEHOLDER_SUBNET_OCID"  # Replace with your worker subnet OCID`)
	p(f, "    }")
	p(f, "  }")
	p(f, "}")
	fmt.Fprintln(f, "")
}

// lineWriter returns a function that writes a line, optionally prefixed with "# " for commenting out.
func lineWriter(commented bool) func(f *os.File, line string) {
	if commented {
		return func(f *os.File, line string) {
			if line == "" {
				fmt.Fprintln(f, "#")
			} else {
				fmt.Fprintf(f, "# %s\n", line)
			}
		}
	}
	return func(f *os.File, line string) {
		fmt.Fprintln(f, line)
	}
}
